/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import models.Food;
import models.DataBaseManager;
import models.Employee;

/**
 *
 * @author Angelo Singh
 */
public class findFood extends javax.swing.JFrame {
    //declaring global variables objects accessible troughout the class
    private Employee loggedInEmployee;
    private List<Food> food;
    private List<Food> foodInSelectedCategory;
    /**
     * Creates new form findFood
     */
    public findFood(Employee employee) {//findFood method
        loggedInEmployee=employee;//set the loggedInEmployee equals to employee
        DataBaseManager db =new DataBaseManager();//create new db object
        food=db.LoadAllFood();//call LoadAllFood function in DataBaseManager
        initComponents();
        
        ButtonGroup bg = new ButtonGroup();//new button object
        //define the following radiobuttons
        bg.add(rdbtnStarter);
        bg.add(rdbtnMain);
        bg.add(rdbtnDessert);

        rdbtnMain.setSelected(true);
        rdbtnMain.doClick();
        
        
    }
    
        public List<Food> getFoodWithinCategory(String category){//getFoodWithinCategory function
        List<Food> foodInCategory= new ArrayList();//create a new List of foods
        
        for(int i=0;i<=food.size()-1;i++){//for every food
            Food foodInList=food.get(i);
            if(foodInList.getCategory().equals(category)){//if food category is equal to the selected category then add it to the foodInList List
                foodInCategory.add(foodInList);
                
            }
        }
        
        return foodInCategory;//return all the food in that specific category
    }
        
        public Food getFood(int foodID){//getFood function
        Food foundFood= null;//set foundFood object= to null
        for(int i=0;i<=food.size()-1;i++){//for every food
            Food foodInList=food.get(i);
            if(foodInList.getFoodID()==foodID){
                foundFood=foodInList;
            }
        }
        return foundFood;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPic1 = new javax.swing.JButton();
        btnPic2 = new javax.swing.JButton();
        btnPic3 = new javax.swing.JButton();
        btnPic4 = new javax.swing.JButton();
        btnPic5 = new javax.swing.JButton();
        rdbtnStarter = new javax.swing.JRadioButton();
        rdbtnMain = new javax.swing.JRadioButton();
        rdbtnDessert = new javax.swing.JRadioButton();
        lblPic1 = new javax.swing.JLabel();
        lblPic2 = new javax.swing.JLabel();
        lblPic3 = new javax.swing.JLabel();
        lblPic4 = new javax.swing.JLabel();
        lblPic5 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPic1.setText("Item1");
        btnPic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPic1ActionPerformed(evt);
            }
        });

        btnPic2.setText("Item2");
        btnPic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPic2ActionPerformed(evt);
            }
        });

        btnPic3.setText("item3");
        btnPic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPic3ActionPerformed(evt);
            }
        });

        btnPic4.setText("item4");
        btnPic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPic4ActionPerformed(evt);
            }
        });

        btnPic5.setText("item5");
        btnPic5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPic5ActionPerformed(evt);
            }
        });

        rdbtnStarter.setText("Starters");
        rdbtnStarter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnStarterActionPerformed(evt);
            }
        });

        rdbtnMain.setText("Mains");
        rdbtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnMainActionPerformed(evt);
            }
        });

        rdbtnDessert.setText("Desserts");
        rdbtnDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDessertActionPerformed(evt);
            }
        });

        lblPic1.setText("jLabel1");

        lblPic2.setText("jLabel2");

        lblPic3.setText("jLabel3");

        lblPic4.setText("jLabel4");

        lblPic5.setText("jLabel5");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnStarter)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnMain)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnDessert)
                        .addGap(112, 112, 112)
                        .addComponent(btnPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPic5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPic2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPic3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(lblPic3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPic5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnStarter)
                            .addComponent(rdbtnMain)
                            .addComponent(rdbtnDessert))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPic3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnPic4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPic5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPic5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPic2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPic3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtnDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDessertActionPerformed
        
        //when this radiobutton is selected 
        foodInSelectedCategory=getFoodWithinCategory("Dessert");//set foodInCategory equal to Dessert
        displayFood();//displayFood method called
    }//GEN-LAST:event_rdbtnDessertActionPerformed

    private void rdbtnStarterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnStarterActionPerformed
        //when this radiobutton is selected
        foodInSelectedCategory=getFoodWithinCategory("Starter");//set foodInCategory equal to Starter
        displayFood();//displayFood method called
    }//GEN-LAST:event_rdbtnStarterActionPerformed

    private void rdbtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnMainActionPerformed
        //when this radiobutton is selected
        foodInSelectedCategory=getFoodWithinCategory("Main");//set foodInCategory equal to Main
        displayFood();//displayFood method called
    }//GEN-LAST:event_rdbtnMainActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        
        //close this window and open home window
           home viewHome= new home(loggedInEmployee);
           this.dispose();
           viewHome.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnPic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPic1ActionPerformed
        //close this window and open viewFood window passing in loggedInEmployee and foodInSelectedCategory
           viewFood viewSpec= new viewFood(loggedInEmployee,foodInSelectedCategory.get(0));
           this.dispose();
           viewSpec.setVisible(true);
    }//GEN-LAST:event_btnPic1ActionPerformed

    private void btnPic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPic2ActionPerformed
        //close this window and open vieewFood window passing in loggedInEmployee and foodInSelectedCategory
        viewFood viewSpec= new viewFood(loggedInEmployee,foodInSelectedCategory.get(1));
           this.dispose();
           viewSpec.setVisible(true);
    }//GEN-LAST:event_btnPic2ActionPerformed

    private void btnPic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPic3ActionPerformed
       //close this window and open viewFood window passing in loggedInEmployee and foodInSelectedCategory
        viewFood viewSpec= new viewFood(loggedInEmployee,foodInSelectedCategory.get(2));
           this.dispose();
           viewSpec.setVisible(true);
    }//GEN-LAST:event_btnPic3ActionPerformed

    private void btnPic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPic4ActionPerformed
        //close this window and open viewFood window passing in loggedInEmployee and foodInSelectedCategory
        viewFood viewSpec= new viewFood(loggedInEmployee,foodInSelectedCategory.get(3));
           this.dispose();
           viewSpec.setVisible(true);
    }//GEN-LAST:event_btnPic4ActionPerformed

    private void btnPic5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPic5ActionPerformed
        //close this window and open viewFood window passing in loggedInEmployee and foodInSelectedCategory
        viewFood viewSpec= new viewFood(loggedInEmployee,foodInSelectedCategory.get(4));
           this.dispose();
           viewSpec.setVisible(true);
    }//GEN-LAST:event_btnPic5ActionPerformed

    
    
    public void displayFood(){//displayFood method
        if(foodInSelectedCategory.size()==0){//if the food in the selected category is 0 then set all buttons and labels to not visible
            btnPic1.setVisible(false);
            btnPic2.setVisible(false);
            btnPic3.setVisible(false);
            lblPic1.setVisible(false);
            lblPic2.setVisible(false);
            lblPic3.setVisible(false);
        }
         if(foodInSelectedCategory.size()>=1){//if the food in the selected category is 1 then set the first button(with corresponding image) and label to visible
            btnPic1.setVisible(true);
            lblPic1.setVisible(true);
            
            Food food1=foodInSelectedCategory.get(0);
            lblPic1.setText(food1.getFoodName());
            
            ImageIcon picture= new ImageIcon(food1.getImage());
            Image image = picture.getImage();
            Image scaledImage=image.getScaledInstance(70,70,image.SCALE_SMOOTH);
            picture = new ImageIcon(scaledImage);
            btnPic1.setText("");
            btnPic1.setIcon(picture);
            
            btnPic2.setVisible(false);
            btnPic3.setVisible(false);
            btnPic4.setVisible(false);
            btnPic5.setVisible(false);
            lblPic4.setVisible(false);
            lblPic5.setVisible(false);
        } if(foodInSelectedCategory.size()>=2){//if the food in the selected category is 2 then set first 2 buttons(with corresponding images) and labels to visible
            btnPic1.setVisible(true);
            lblPic1.setVisible(true);
            btnPic2.setVisible(true);
            lblPic2.setVisible(true);
            Food food2 =foodInSelectedCategory.get(1);
            lblPic2.setText(food2.getFoodName());
            ImageIcon picture2= new ImageIcon(food2.getImage());
            Image image2 = picture2.getImage();
            Image scaledImage2=image2.getScaledInstance(70,70,image2.SCALE_SMOOTH);
            picture2 = new ImageIcon(scaledImage2);
            btnPic2.setText("");
            btnPic2.setIcon(picture2);
            
            btnPic3.setVisible(false);
            btnPic4.setVisible(false);
            btnPic5.setVisible(false);
            lblPic3.setVisible(false);
            lblPic4.setVisible(false);
            lblPic5.setVisible(false);
            
        } if(foodInSelectedCategory.size()>=3){//if the food in the selected category is 3 then set all 3 buttons(with corresponding images) and labels to visible
            btnPic1.setVisible(true);
            btnPic2.setVisible(true);
            btnPic3.setVisible(true);
            lblPic1.setVisible(true);
            lblPic2.setVisible(true);
            lblPic3.setVisible(true);
            Food food3 =foodInSelectedCategory.get(2);
            lblPic3.setText(food3.getFoodName());
            ImageIcon picture3= new ImageIcon(food3.getImage());
            Image image3 = picture3.getImage();
            Image scaledImage3=image3.getScaledInstance(70,70,image3.SCALE_SMOOTH);
            picture3 = new ImageIcon(scaledImage3);
            btnPic3.setText("");
            btnPic3.setIcon(picture3);
            
            
            btnPic4.setVisible(false);
            btnPic5.setVisible(false);
            
            lblPic4.setVisible(false);
            lblPic5.setVisible(false);
        }if(foodInSelectedCategory.size()>=4){//if the food in the selected category is 4 then set all 4 buttons (with corresponding images) and label to visibles
            btnPic1.setVisible(true);
            btnPic2.setVisible(true);
            btnPic3.setVisible(true);
            btnPic4.setVisible(true);
            lblPic1.setVisible(true);
            lblPic2.setVisible(true);
            lblPic3.setVisible(true);
            lblPic4.setVisible(true);
            Food food4 =foodInSelectedCategory.get(3);
            lblPic4.setText(food4.getFoodName());
            ImageIcon picture4= new ImageIcon(food4.getImage());
            Image image4 = picture4.getImage();
            Image scaledImage4=image4.getScaledInstance(70,70,image4.SCALE_SMOOTH);
            picture4 = new ImageIcon(scaledImage4);
            btnPic4.setText("");
            btnPic4.setIcon(picture4);
            
         
            btnPic5.setVisible(false);
            
            lblPic5.setVisible(false);
        }if(foodInSelectedCategory.size()>=5){//if the food in the selected category is 5 then set all five buttons(with corresponding images) and labels to visible
            btnPic1.setVisible(true);
            btnPic2.setVisible(true);
            btnPic3.setVisible(true);
            btnPic4.setVisible(true);
            btnPic5.setVisible(true);
            lblPic1.setVisible(true);
            lblPic2.setVisible(true);
            lblPic3.setVisible(true);
            lblPic4.setVisible(true);
            lblPic5.setVisible(true);
            Food food5 =foodInSelectedCategory.get(4);
            lblPic5.setText(food5.getFoodName());
            ImageIcon picture5= new ImageIcon(food5.getImage());
            Image image5 = picture5.getImage();
            Image scaledImage5=image5.getScaledInstance(70,70,image5.SCALE_SMOOTH);
            picture5 = new ImageIcon(scaledImage5);
            btnPic5.setText("");
            btnPic5.setIcon(picture5);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(findFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(findFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(findFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(findFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new findFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnPic1;
    private javax.swing.JButton btnPic2;
    private javax.swing.JButton btnPic3;
    private javax.swing.JButton btnPic4;
    private javax.swing.JButton btnPic5;
    private javax.swing.JLabel lblPic1;
    private javax.swing.JLabel lblPic2;
    private javax.swing.JLabel lblPic3;
    private javax.swing.JLabel lblPic4;
    private javax.swing.JLabel lblPic5;
    private javax.swing.JRadioButton rdbtnDessert;
    private javax.swing.JRadioButton rdbtnMain;
    private javax.swing.JRadioButton rdbtnStarter;
    // End of variables declaration//GEN-END:variables
}
